# Generated by Django 5.2.4 on 2025-07-26 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('operation_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('parameters', models.CharField(max_length=30)),
                ('result', models.CharField(max_length=30)),
                ('inclusion', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
